apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sleep"]
      args: ["100000"]
      volumeMounts:
        - mountPath: /etc/config # 생성한 ConfigMap /etc/config 디렉토리에 연결
          name: config-vol
  volumes:
    - name: config-vol
      # 생성한 ConfigMap /etc/config 디렉토리에 연결
      configMap:
        name: my-config