apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  # 컨테이너 간 디렉토리 공유
  containers:
    - name: app
      image: busybox
      args:
        - /bin/sh
        - -c
        - >
          while true;
          do
            echo "$(date)\n" >> /var/log/example.log;
            sleep 1;
          done
      volumeMounts:
        - mountPath: /var/log # 로그파일 생성
          name: varlog
    - name: sidecar
      image: busybox
      args: [/bin/sh, -c, "tail -f /var/log/example.log"]
      volumeMounts:
        - mountPath: /var/log
          name: varlog
  volumes:
    - name: varlog
      emptyDir: {}