apiVersion: v1
kind: Service
metadata:
  name: counter-np
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 31000 # 노드에 오픈할 Port (미지정시 30000~32768 중 자동 할당)
  selector:
    app: counter
    tier: app