apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              name: jenkins
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins
      volumes:
        - name: jenkins
          hostPath:
            path: /Users/juhwan/jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: jenkins




