apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter
spec:
  # 다중 컨테이너
  # 로그확인 : kubectl logs counter {컨테이너명}
  containers:
    - name: app
      image: ghcr.io/subicura/counter
      env:
        - name: REDIS_HOST
          value: "localhost"
    - name: db
      image: redis